export const storybookCopy = {
  colorGuides: {
    eyebrow: "Foundations",
    title: "Color Guides",
    lead:
      "Color guidance distilled from design-system evidence and the current token architecture. Use system color roles for product semantics, then bind component slots to those roles.",
    rulesTitle: "Color operating rules",
    semanticTitle: "Semantic color roles",
    referenceTitle: "Reference palette",
    tokenLabel: "Token",
    foregroundLabel: "Foreground",
    valueLabel: "Authored",
    resolvedLabel: "Resolved",
    guidanceLabel: "Use",
    avoidLabel: "Avoid",
    noForeground: "No paired foreground token",
    unknownValue: "Unknown token",
    rules: [
      "Product UI uses the dark shell first: background, surface, raised surface, and hover surface are functional depth levels, not decorative panels.",
      "Filled surfaces must use the matching on-* foreground role whenever one exists. Do not assume white or black text.",
      "Taiwan market data keeps red as up/gain and green as down/loss. Do not remap these colors to generic error or success.",
      "Portfolio category, valuation, event, and temporal colors are separate semantic languages. Reuse the named role, not the nearest hue.",
      "Reference colors are raw palette steps. Component code should consume system or component tokens instead of ref tokens.",
    ],
    sections: [
      {
        title: "Dark Shell And Surfaces",
        summary:
          "Core shell colors create compact product depth for trading screens, sheets, rows, and utility bars.",
        roles: [
          {
            label: "App background",
            token: "--sbt-sys-color-background",
            onToken: "--sbt-sys-color-on-background",
            guidance: "Use for the app canvas and flat list background.",
            avoid: "Do not replace it with gradients, hero treatments, or decorative page chrome.",
          },
          {
            label: "Default surface",
            token: "--sbt-sys-color-surface",
            onToken: "--sbt-sys-color-on-surface",
            guidance: "Use for bottom sheets, sheet rows, compact panels, and stable module fills.",
            avoid: "Do not use it as a generic card stack surface when the source is table-led.",
          },
          {
            label: "Raised surface",
            token: "--sbt-sys-color-surface-raised",
            onToken: "--sbt-sys-color-on-surface-raised",
            guidance: "Use for app bars, list headers, selected nav containers, and raised row chrome.",
            avoid: "Do not add shadows unless a component token already defines the shadow.",
          },
          {
            label: "Hover surface",
            token: "--sbt-sys-color-surface-hover",
            onToken: "--sbt-sys-color-on-surface-hover",
            guidance: "Use for compact hover/active surface steps inside dark controls.",
            avoid: "Do not use hover color as a permanent selected state without a component slot.",
          },
          {
            label: "Inverse surface",
            token: "--sbt-sys-color-inverse",
            onToken: "--sbt-sys-color-on-inverse",
            guidance: "Use only where the design explicitly needs a light surface on the dark shell.",
            avoid: "Do not introduce broad light-mode panels from this token alone.",
          },
        ],
      },
      {
        title: "Brand And Action",
        summary:
          "Warm brand roles cover primary actions, secondary amber controls, promo treatments, and neutral utility actions.",
        roles: [
          {
            label: "Primary action",
            token: "--sbt-sys-color-primary",
            onToken: "--sbt-sys-color-on-primary",
            guidance: "Use for filled primary action containers and primary selected marks.",
            avoid: "Do not use primary orange to imply market movement or event severity.",
          },
          {
            label: "Primary pressed",
            token: "--sbt-sys-color-primary-pressed",
            onToken: "--sbt-sys-color-on-primary-pressed",
            guidance: "Use for pressed primary action state.",
            avoid: "Do not use this as the default orange when no pressed state is present.",
          },
          {
            label: "Primary container",
            token: "--sbt-sys-color-primary-container",
            onToken: "--sbt-sys-color-on-primary-container",
            guidance: "Use for pale orange filled fields and container treatments evidenced in forms.",
            avoid: "Do not use it as a generic warning color.",
          },
          {
            label: "Secondary action",
            token: "--sbt-sys-color-secondary",
            onToken: "--sbt-sys-color-on-secondary",
            guidance: "Use for amber controls, event estimates, and secondary action semantics.",
            avoid: "Do not merge it with allocation-series amber without a chart-specific role.",
          },
          {
            label: "Warm highlight",
            token: "--sbt-sys-color-highlight-warm",
            onToken: "--sbt-sys-color-on-highlight-warm",
            guidance: "Use for compact warm emphasis text and highlight surfaces.",
            avoid: "Do not turn it into promo badge chrome; promo roles are separate.",
          },
          {
            label: "Neutral action",
            token: "--sbt-sys-color-action-neutral",
            onToken: "--sbt-sys-color-on-action-neutral",
            guidance: "Use for floating neutral actions and selected warm-gray controls.",
            avoid: "Do not use it as a disabled state; disabled tokens already exist.",
          },
        ],
      },
      {
        title: "Market And Main Force",
        summary:
          "Market roles preserve Taiwan stock convention, while main-force roles stay separate from generic market movement.",
        roles: [
          {
            label: "Market up",
            token: "--sbt-sys-color-market-up",
            onToken: "--sbt-sys-color-on-market-up",
            guidance: "Use for upward/gain market values and gain bars in Taiwan market contexts.",
            avoid: "Do not use red as generic error inside market views.",
          },
          {
            label: "Market up dim",
            token: "--sbt-sys-color-market-up-dim",
            onToken: "--sbt-sys-color-on-market-up-dim",
            guidance: "Use for dark red market-depth surfaces.",
            avoid: "Do not use it for destructive confirmations.",
          },
          {
            label: "Market down",
            token: "--sbt-sys-color-market-down",
            onToken: "--sbt-sys-color-on-market-down",
            guidance: "Use for downward/loss market values and loss bars in Taiwan market contexts.",
            avoid: "Do not use green as generic success inside market views.",
          },
          {
            label: "Market down wash",
            token: "--sbt-sys-color-market-down-wash",
            onToken: "--sbt-sys-color-on-market-down-wash",
            guidance: "Use for muted green market surfaces that still indicate downside movement.",
            avoid: "Do not reuse it for portfolio category color.",
          },
          {
            label: "Market auction",
            token: "--sbt-sys-color-market-auction",
            onToken: "--sbt-sys-color-on-market-auction",
            guidance: "Use for auction-specific market state.",
            avoid: "Do not use it as a generic brown neutral.",
          },
          {
            label: "Main-force buy",
            token: "--sbt-sys-color-main-force-buy",
            guidance: "Use for main-force buy indicators where the component contract names that role.",
            avoid: "Do not collapse it into market-up when the source is main-force behavior.",
          },
          {
            label: "Overnight trade tag",
            token: "--sbt-sys-color-main-force-overnight-trade",
            guidance: "Use for main-force overnight-trade tag color.",
            avoid: "Do not use it as promotional badge yellow.",
          },
          {
            label: "Short trade tag",
            token: "--sbt-sys-color-main-force-short-trade",
            guidance: "Use for main-force short-trade tag color.",
            avoid: "Do not use it as market-up or status-new red.",
          },
        ],
      },
      {
        title: "Portfolio And Analytics",
        summary:
          "Portfolio colors distinguish holding attributes, fit assessment, health checks, allocation charts, and valuation labels.",
        roles: [
          {
            label: "Long-term",
            token: "--sbt-sys-color-portfolio-long-term",
            onToken: "--sbt-sys-color-on-portfolio-long-term",
            guidance: "Use for long-term holding attribute labels and related bars.",
            avoid: "Do not reuse it for cheap valuation unless the valuation token says so.",
          },
          {
            label: "Swing",
            token: "--sbt-sys-color-portfolio-swing",
            onToken: "--sbt-sys-color-on-portfolio-swing",
            guidance: "Use for swing holding attribute labels and related bars.",
            avoid: "Do not use it as secondary action by hue alone.",
          },
          {
            label: "Short-term",
            token: "--sbt-sys-color-portfolio-short-term",
            onToken: "--sbt-sys-color-on-portfolio-short-term",
            guidance: "Use for short-term holding attribute labels and related bars.",
            avoid: "Do not map it to market-up or error semantics.",
          },
          {
            label: "Unclassified",
            token: "--sbt-sys-color-portfolio-unclassified",
            onToken: "--sbt-sys-color-on-portfolio-unclassified",
            guidance: "Use for unclassified portfolio attribute state.",
            avoid: "Do not use it as a generic disabled fill.",
          },
          {
            label: "Fit match",
            token: "--sbt-sys-color-fit-assessment-match",
            guidance: "Use for fit-assessment match icon/state only.",
            avoid: "Do not use it as market-up unless the component is market data.",
          },
          {
            label: "Fit mismatch",
            token: "--sbt-sys-color-fit-assessment-mismatch",
            guidance: "Use for fit-assessment mismatch icon/state only.",
            avoid: "Do not use it as generic success or market-down outside fit assessment.",
          },
          {
            label: "Health note",
            token: "--sbt-sys-color-portfolio-health-note",
            guidance: "Use for portfolio health note and exception count emphasis.",
            avoid: "Do not reuse it as temporal current/future date color.",
          },
          {
            label: "Allocation series 1",
            token: "--sbt-sys-color-portfolio-allocation-series-1",
            guidance: "Use for allocation chart series only.",
            avoid: "Do not reuse chart series colors as holding attribute colors.",
          },
          {
            label: "Allocation series 2",
            token: "--sbt-sys-color-portfolio-allocation-series-2",
            guidance: "Use for allocation chart series only.",
            avoid: "Do not reuse chart series colors as market or status semantics.",
          },
          {
            label: "Allocation series 3",
            token: "--sbt-sys-color-portfolio-allocation-series-3",
            guidance: "Use for allocation chart series only.",
            avoid: "Do not introduce purple as a generic brand accent.",
          },
          {
            label: "Allocation series 4",
            token: "--sbt-sys-color-portfolio-allocation-series-4",
            guidance: "Use for allocation chart series only.",
            avoid: "Do not use it for valuation or broker identity.",
          },
          {
            label: "Allocation series 5",
            token: "--sbt-sys-color-portfolio-allocation-series-5",
            guidance: "Use for allocation chart series only.",
            avoid: "Do not reuse it for warning or new-state badges.",
          },
          {
            label: "Valuation expensive",
            token: "--sbt-sys-color-valuation-expensive",
            onToken: "--sbt-sys-color-on-valuation-expensive",
            guidance: "Use for expensive valuation labels.",
            avoid: "Do not infer market-up movement from this orange.",
          },
          {
            label: "Valuation slightly high",
            token: "--sbt-sys-color-valuation-slightly-high",
            onToken: "--sbt-sys-color-on-valuation-slightly-high",
            guidance: "Use for slightly-high valuation labels.",
            avoid: "Do not use it as form warning.",
          },
          {
            label: "Valuation slightly low",
            token: "--sbt-sys-color-valuation-slightly-low",
            onToken: "--sbt-sys-color-on-valuation-slightly-low",
            guidance: "Use for slightly-low valuation labels.",
            avoid: "Do not use it as long-term portfolio category blue.",
          },
          {
            label: "Valuation cheap",
            token: "--sbt-sys-color-valuation-cheap",
            onToken: "--sbt-sys-color-on-valuation-cheap",
            guidance: "Use for cheap valuation labels.",
            avoid: "Do not reuse it for chart series or portfolio attributes.",
          },
        ],
      },
      {
        title: "Events, Temporal, Selection, Status",
        summary:
          "Calendar/event colors are metadata-led. Selection and status colors remain compact component states.",
        roles: [
          {
            label: "Temporal current",
            token: "--sbt-sys-color-temporal-current",
            guidance: "Use for current date labels.",
            avoid: "Do not treat it as warning, gain, or health-note color.",
          },
          {
            label: "Temporal future",
            token: "--sbt-sys-color-temporal-future",
            guidance: "Use for future date labels.",
            avoid: "Do not use it for event severity.",
          },
          {
            label: "Temporal past",
            token: "--sbt-sys-color-temporal-past",
            guidance: "Use for past date labels.",
            avoid: "Do not use it as disabled text when disabled tokens exist.",
          },
          {
            label: "Event name",
            token: "--sbt-sys-color-event-name",
            guidance: "Use for financial event metadata labels.",
            avoid: "Do not infer clickability from orange event text alone.",
          },
          {
            label: "Event stock name",
            token: "--sbt-sys-color-event-stock-name",
            guidance: "Use for stock names inside event table rows.",
            avoid: "Do not merge it with temporal yellow without a token decision.",
          },
          {
            label: "Selection option default",
            token: "--sbt-sys-color-selection-option-default",
            onToken: "--sbt-sys-color-on-selection-option-default",
            guidance: "Use for neutral event filter option fills.",
            avoid: "Do not use this as generic card fill.",
          },
          {
            label: "Selection option selected",
            token: "--sbt-sys-color-selection-option-selected",
            onToken: "--sbt-sys-color-on-selection-option-selected",
            guidance: "Use for selected event filter option fills.",
            avoid: "Do not use selected fill where the component only changes label color.",
          },
          {
            label: "New status",
            token: "--sbt-sys-color-status-new",
            onToken: "--sbt-sys-color-on-status-new",
            guidance: "Use for the compact red New badge.",
            avoid: "Do not reuse it for market-up, duplicate warning, or promotions.",
          },
        ],
      },
      {
        title: "Control, Outline, Annotation",
        summary:
          "Control and annotation roles cover compact chrome, borders, transparent slots, and QA-only overlays.",
        roles: [
          {
            label: "Control neutral",
            token: "--sbt-sys-color-control-neutral",
            onToken: "--sbt-sys-color-on-control",
            guidance: "Use for compact neutral controls on dark surfaces.",
            avoid: "Do not use it as the page background.",
          },
          {
            label: "Control selected",
            token: "--sbt-sys-color-control-selected",
            onToken: "--sbt-sys-color-on-control-selected",
            guidance: "Use for selected compact controls where warm-gray is evidenced.",
            avoid: "Do not replace primary selected marks with this token.",
          },
          {
            label: "Action subtle",
            token: "--sbt-sys-color-action-subtle",
            onToken: "--sbt-sys-color-on-surface-strong",
            guidance: "Use for subtle dark action rows and sheet action fills.",
            avoid: "Do not make it a generic dashboard card background.",
          },
          {
            label: "Disabled container",
            token: "--sbt-sys-color-disabled-container",
            onToken: "--sbt-sys-color-on-disabled-container",
            guidance: "Use for disabled filled controls.",
            avoid: "Do not use disabled text and disabled container interchangeably.",
          },
          {
            label: "Outline",
            token: "--sbt-sys-color-outline",
            guidance: "Use for compact borders and control outlines.",
            avoid: "Do not use outline roles as filled surfaces.",
          },
          {
            label: "Inverse outline",
            token: "--sbt-sys-color-outline-inverse",
            guidance: "Use for subtle separators on dark surfaces.",
            avoid: "Do not use alpha outlines as text colors.",
          },
          {
            label: "Annotation fixed",
            token: "--sbt-sys-color-annotation-fixed",
            guidance: "Use only for specs and design QA overlays.",
            avoid: "Do not ship annotation colors in product UI.",
          },
          {
            label: "Annotation flow",
            token: "--sbt-sys-color-annotation-flow",
            guidance: "Use only for specs and design QA overlays.",
            avoid: "Do not use annotation purple as a product accent.",
          },
        ],
      },
    ],
    palettes: [
      {
        title: "Warm Brand Ramp",
        summary: "Raw orange, peach, amber, and yellow values behind brand, promo, event, and temporal roles.",
        tokens: [
          { label: "Orange 12", token: "--sbt-ref-color-orange-12" },
          { label: "Orange 36", token: "--sbt-ref-color-orange-36" },
          { label: "Orange 50", token: "--sbt-ref-color-orange-50" },
          { label: "Orange 60", token: "--sbt-ref-color-orange-60" },
          { label: "Orange 75", token: "--sbt-ref-color-orange-75" },
          { label: "Orange 88", token: "--sbt-ref-color-orange-88" },
          { label: "Orange 96", token: "--sbt-ref-color-orange-96" },
          { label: "Peach 92", token: "--sbt-ref-color-peach-92" },
          { label: "Amber 50", token: "--sbt-ref-color-amber-50" },
          { label: "Amber 60", token: "--sbt-ref-color-amber-60" },
          { label: "Amber 62", token: "--sbt-ref-color-amber-62" },
          { label: "Amber 75", token: "--sbt-ref-color-amber-75" },
          { label: "Yellow 64", token: "--sbt-ref-color-yellow-64" },
          { label: "Yellow 68", token: "--sbt-ref-color-yellow-68" },
          { label: "Yellow 94", token: "--sbt-ref-color-yellow-94" },
          { label: "Yellow 95", token: "--sbt-ref-color-yellow-95" },
          { label: "Yellow 96", token: "--sbt-ref-color-yellow-96" },
        ],
      },
      {
        title: "Neutral Ramp",
        summary: "Raw dark-shell, surface, outline, disabled, and text contrast steps.",
        tokens: [
          { label: "Neutral 0", token: "--sbt-ref-color-neutral-0" },
          { label: "Neutral 12", token: "--sbt-ref-color-neutral-12" },
          { label: "Neutral 15", token: "--sbt-ref-color-neutral-15" },
          { label: "Neutral 20", token: "--sbt-ref-color-neutral-20" },
          { label: "Neutral 24", token: "--sbt-ref-color-neutral-24" },
          { label: "Neutral 29", token: "--sbt-ref-color-neutral-29" },
          { label: "Neutral 32", token: "--sbt-ref-color-neutral-32" },
          { label: "Neutral 36", token: "--sbt-ref-color-neutral-36" },
          { label: "Neutral 46", token: "--sbt-ref-color-neutral-46" },
          { label: "Neutral 50", token: "--sbt-ref-color-neutral-50" },
          { label: "Neutral 56", token: "--sbt-ref-color-neutral-56" },
          { label: "Neutral 60", token: "--sbt-ref-color-neutral-60" },
          { label: "Neutral 75", token: "--sbt-ref-color-neutral-75" },
          { label: "Neutral 85", token: "--sbt-ref-color-neutral-85" },
          { label: "Neutral 100", token: "--sbt-ref-color-neutral-100" },
          { label: "Lavender 94", token: "--sbt-ref-color-lavender-94" },
          { label: "Warm gray 50", token: "--sbt-ref-color-warm-gray-50" },
        ],
      },
      {
        title: "Market And Status Hues",
        summary: "Raw reds, greens, brown, and related high-signal hues behind market, status, and main-force roles.",
        tokens: [
          { label: "Red 25", token: "--sbt-ref-color-red-25" },
          { label: "Red 60", token: "--sbt-ref-color-red-60" },
          { label: "Red 62", token: "--sbt-ref-color-red-62" },
          { label: "Red 65", token: "--sbt-ref-color-red-65" },
          { label: "Red 77", token: "--sbt-ref-color-red-77" },
          { label: "Green 15", token: "--sbt-ref-color-green-15" },
          { label: "Green 25", token: "--sbt-ref-color-green-25" },
          { label: "Green 35", token: "--sbt-ref-color-green-35" },
          { label: "Green 55", token: "--sbt-ref-color-green-55" },
          { label: "Brown 40", token: "--sbt-ref-color-brown-40" },
        ],
      },
      {
        title: "Portfolio And Chart Hues",
        summary: "Raw portfolio attribute, valuation, and chart series hues.",
        tokens: [
          { label: "Blue 60", token: "--sbt-ref-color-blue-60" },
          { label: "Sky 96", token: "--sbt-ref-color-sky-96" },
          { label: "Rose 55", token: "--sbt-ref-color-rose-55" },
          { label: "Pink 60", token: "--sbt-ref-color-pink-60" },
          { label: "Purple 55", token: "--sbt-ref-color-purple-55" },
          { label: "Cyan 47", token: "--sbt-ref-color-cyan-47" },
          { label: "Vermilion 56", token: "--sbt-ref-color-vermilion-56" },
        ],
      },
      {
        title: "Alpha And Annotation",
        summary: "Raw transparent paints and QA annotation colors. Annotation colors are not product UI colors.",
        tokens: [
          { label: "White alpha 0", token: "--sbt-ref-color-white-alpha-0" },
          { label: "White alpha 8", token: "--sbt-ref-color-white-alpha-8" },
          { label: "White alpha 20", token: "--sbt-ref-color-white-alpha-20" },
          { label: "Orange alpha 60", token: "--sbt-ref-color-orange-alpha-60" },
          { label: "Yellow alpha 80", token: "--sbt-ref-color-yellow-70-alpha-80" },
          { label: "Mint alpha 60", token: "--sbt-ref-color-mint-60-alpha-60" },
          { label: "Pink 70", token: "--sbt-ref-color-pink-70" },
          { label: "Violet 70", token: "--sbt-ref-color-violet-70" },
        ],
      },
    ],
  },
  tokenCatalog: {
    eyebrow: "Foundations",
    title: "Token Catalog",
    lead:
      "Storybook reads the existing CSS token files and shows each reference, system, and component token with its authored value and browser-resolved value.",
    summaryLabel: "Token summary",
    layerLabel: "Layer",
    familyLabel: "Family",
    allLayers: "All layers",
    allFamilies: "All families",
    tokenColumn: "Token",
    valueColumn: "Authored value",
    resolvedColumn: "Resolved value",
    previewColumn: "Preview",
    noPreview: "No visual preview",
    emptyState: "No tokens match the selected filters.",
  },
  typographyGuides: {
    eyebrow: "Foundations",
    title: "Typography Guide",
    lead:
      "Typography guidance for the current dense trading UI. Use system typeface, weight, and typescale roles directly, then bind component slots to the same roles.",
    typefaceTitle: "Typeface roles",
    typescaleTitle: "Type scale roles",
    rulesTitle: "Typography operating rules",
    tokenLabel: "Token",
    typefaceLabel: "Typeface",
    weightLabel: "Weight",
    sizeLabel: "Size",
    lineHeightLabel: "Line height",
    valueLabel: "Authored",
    resolvedLabel: "Resolved",
    usageLabel: "Use",
    unknownValue: "Unknown token",
    rules: [
      "Default product text uses the plain CJK-first stack, with Latin and CJK support roles as fallback layers.",
      "Financial values and compact numeric columns use numeric roles so figure rhythm stays stable across rows.",
      "Type scale roles are semantic product roles, not a generic heading ladder. Reuse the role that matches the product context.",
      "Component code should consume sys or comp type tokens. Do not bypass the system layer with raw ref size values.",
    ],
    typefaces: [
      {
        label: "Plain UI",
        token: "--sbt-sys-typeface-plain",
        sample: "台股庫存與自選股",
        guidance: "Primary interface copy and dense CJK product labels.",
      },
      {
        label: "Latin UI",
        token: "--sbt-sys-typeface-latin",
        sample: "Portfolio Holdings",
        guidance: "Latin fallback and token/documentation labels.",
      },
      {
        label: "Status Latin",
        token: "--sbt-sys-typeface-status-latin",
        sample: "NEW",
        guidance: "Short status labels where the source uses a distinct Latin face.",
      },
      {
        label: "CJK Support",
        token: "--sbt-sys-typeface-cjk-support",
        sample: "決算短信",
        guidance: "Japanese/CJK support text when glyph coverage needs a secondary CJK face.",
      },
      {
        label: "Numeric",
        token: "--sbt-sys-typeface-numeric",
        sample: "123.45",
        guidance: "Prominent numeric display and score values.",
      },
      {
        label: "Financial Numeric",
        token: "--sbt-sys-typeface-financial-numeric",
        sample: "+12,345",
        guidance: "Portfolio profit, cost, and tabular financial values.",
      },
    ],
    sections: [
      {
        title: "Titles And Content",
        summary:
          "Dense product surfaces rely on compact titles, body, and message roles rather than oversized editorial typography.",
        roles: [
          {
            label: "Title LG",
            sizeToken: "--sbt-sys-typescale-title-lg-size",
            lineHeightToken: "--sbt-sys-typescale-title-lg-line-height",
            weightToken: "--sbt-sys-weight-semibold",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "庫存股總覽",
            guidance: "Top-level compact section titles.",
          },
          {
            label: "Title MD",
            sizeToken: "--sbt-sys-typescale-title-md-size",
            lineHeightToken: "--sbt-sys-typescale-title-md-line-height",
            weightToken: "--sbt-sys-weight-semibold",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "持股分析速配",
            guidance: "Sheet headers, row names, and primary compact headings.",
          },
          {
            label: "Title MD Compact",
            sizeToken: "--sbt-sys-typescale-title-md-compact-size",
            lineHeightToken: "--sbt-sys-typescale-title-md-compact-line-height",
            weightToken: "--sbt-sys-weight-semibold",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "重大事件",
            guidance: "Title contexts that must align with normal line-height rows.",
          },
          {
            label: "Title SM",
            sizeToken: "--sbt-sys-typescale-title-sm-size",
            lineHeightToken: "--sbt-sys-typescale-title-sm-line-height",
            weightToken: "--sbt-sys-weight-semibold",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "交易明細",
            guidance: "Subsection titles and compact labels with stronger hierarchy.",
          },
          {
            label: "Body SM",
            sizeToken: "--sbt-sys-typescale-body-sm-size",
            lineHeightToken: "--sbt-sys-typescale-body-sm-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "每列保留清楚的資訊密度。",
            guidance: "Default explanatory text and row descriptions.",
          },
          {
            label: "Message SM",
            sizeToken: "--sbt-sys-typescale-message-sm-size",
            lineHeightToken: "--sbt-sys-typescale-message-sm-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "尚未匯入任何庫存資料。",
            guidance: "Empty, helper, and small message copy.",
          },
        ],
      },
      {
        title: "Market Data And Numeric",
        summary:
          "Numeric roles separate financial rhythm from generic body copy and preserve compact comparison across columns.",
        roles: [
          {
            label: "Score LG",
            sizeToken: "--sbt-sys-typescale-score-lg-size",
            lineHeightToken: "--sbt-sys-typescale-score-lg-line-height",
            weightToken: "--sbt-sys-weight-semibold",
            typefaceToken: "--sbt-sys-typeface-numeric",
            sample: "87",
            guidance: "Large score and assessment values.",
          },
          {
            label: "Signal LG",
            sizeToken: "--sbt-sys-typescale-signal-lg-size",
            lineHeightToken: "--sbt-sys-typescale-signal-lg-line-height",
            weightToken: "--sbt-sys-weight-semibold",
            typefaceToken: "--sbt-sys-typeface-numeric",
            sample: "買超",
            guidance: "High-emphasis market signal labels.",
          },
          {
            label: "Profit Value",
            sizeToken: "--sbt-sys-typescale-profit-value-size",
            lineHeightToken: "--sbt-sys-typescale-profit-value-line-height",
            weightToken: "--sbt-sys-weight-semibold",
            typefaceToken: "--sbt-sys-typeface-financial-numeric",
            sample: "+12,345",
            guidance: "Primary portfolio profit amount.",
          },
          {
            label: "Profit Rate",
            sizeToken: "--sbt-sys-typescale-profit-rate-size",
            lineHeightToken: "--sbt-sys-typescale-profit-rate-line-height",
            weightToken: "--sbt-sys-weight-medium",
            typefaceToken: "--sbt-sys-typeface-financial-numeric",
            sample: "+8.52%",
            guidance: "Secondary rate values paired with profit amount.",
          },
          {
            label: "Numeric LG",
            sizeToken: "--sbt-sys-typescale-numeric-lg-size",
            lineHeightToken: "--sbt-sys-typescale-numeric-lg-line-height",
            weightToken: "--sbt-sys-weight-medium",
            typefaceToken: "--sbt-sys-typeface-numeric",
            sample: "146.50",
            guidance: "Table values and larger numeric columns.",
          },
          {
            label: "Numeric MD",
            sizeToken: "--sbt-sys-typescale-numeric-md-size",
            lineHeightToken: "--sbt-sys-typescale-numeric-md-line-height",
            weightToken: "--sbt-sys-weight-medium",
            typefaceToken: "--sbt-sys-typeface-numeric",
            sample: "2,810",
            guidance: "Secondary numeric cells and compact metrics.",
          },
          {
            label: "Metric SM",
            sizeToken: "--sbt-sys-typescale-metric-sm-size",
            lineHeightToken: "--sbt-sys-typescale-metric-sm-line-height",
            weightToken: "--sbt-sys-weight-medium",
            typefaceToken: "--sbt-sys-typeface-numeric",
            sample: "31.8%",
            guidance: "Small metrics, chart labels, and report rows.",
          },
        ],
      },
      {
        title: "Labels, Metadata, Tables",
        summary:
          "Labels and metadata keep supporting information scannable without competing with stock names and financial values.",
        roles: [
          {
            label: "Label XL",
            sizeToken: "--sbt-sys-typescale-label-xl-size",
            lineHeightToken: "--sbt-sys-typescale-label-xl-line-height",
            weightToken: "--sbt-sys-weight-medium",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "長期存股",
            guidance: "Prominent label text in compact rows.",
          },
          {
            label: "Label LG",
            sizeToken: "--sbt-sys-typescale-label-lg-size",
            lineHeightToken: "--sbt-sys-typescale-label-lg-line-height",
            weightToken: "--sbt-sys-weight-medium",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "新增庫存",
            guidance: "Action labels and selected compact controls.",
          },
          {
            label: "Label MD",
            sizeToken: "--sbt-sys-typescale-label-md-size",
            lineHeightToken: "--sbt-sys-typescale-label-md-line-height",
            weightToken: "--sbt-sys-weight-medium",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "評價合理",
            guidance: "Default label text with readable row height.",
          },
          {
            label: "Label SM",
            sizeToken: "--sbt-sys-typescale-label-sm-size",
            lineHeightToken: "--sbt-sys-typescale-label-sm-line-height",
            weightToken: "--sbt-sys-weight-medium",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "已分類",
            guidance: "Small labels and compact metadata tags.",
          },
          {
            label: "Caption SM",
            sizeToken: "--sbt-sys-typescale-caption-sm-size",
            lineHeightToken: "--sbt-sys-typescale-caption-sm-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "資料更新於 14:30",
            guidance: "Caption copy and low-emphasis helper text.",
          },
          {
            label: "Metadata SM",
            sizeToken: "--sbt-sys-typescale-metadata-sm-size",
            lineHeightToken: "--sbt-sys-typescale-metadata-sm-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "TWSE · 2330",
            guidance: "Secondary metadata beside names and labels.",
          },
          {
            label: "Metadata XS",
            sizeToken: "--sbt-sys-typescale-metadata-xs-size",
            lineHeightToken: "--sbt-sys-typescale-metadata-xs-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "ADR",
            guidance: "Very compact metadata where horizontal room is constrained.",
          },
          {
            label: "Metadata XXS",
            sizeToken: "--sbt-sys-typescale-metadata-xxs-size",
            lineHeightToken: "--sbt-sys-typescale-metadata-xxs-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "盤後",
            guidance: "Smallest metadata role; avoid for primary information.",
          },
          {
            label: "Table Header",
            sizeToken: "--sbt-sys-typescale-table-header-size",
            lineHeightToken: "--sbt-sys-typescale-table-header-line-height",
            weightToken: "--sbt-sys-weight-medium",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "殖利率",
            guidance: "Column headers and sort labels.",
          },
          {
            label: "Chart Axis",
            sizeToken: "--sbt-sys-typescale-chart-axis-size",
            lineHeightToken: "--sbt-sys-typescale-chart-axis-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-numeric",
            sample: "0 25 50 75",
            guidance: "Tiny chart axis labels only.",
          },
          {
            label: "Allocation Legend",
            sizeToken: "--sbt-sys-typescale-allocation-legend-size",
            lineHeightToken: "--sbt-sys-typescale-allocation-legend-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "半導體 42%",
            guidance: "Allocation legend labels and chart summaries.",
          },
        ],
      },
      {
        title: "Domain-Specific Roles",
        summary:
          "These roles exist because the source components have specific density, language, or status requirements.",
        roles: [
          {
            label: "Broker Icon Label",
            sizeToken: "--sbt-sys-typescale-broker-icon-label-size",
            lineHeightToken: "--sbt-sys-typescale-broker-icon-label-line-height",
            weightToken: "--sbt-sys-weight-medium",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "富邦",
            guidance: "Broker icon captions.",
          },
          {
            label: "Date MD",
            sizeToken: "--sbt-sys-typescale-date-md-size",
            lineHeightToken: "--sbt-sys-typescale-date-md-line-height",
            weightToken: "--sbt-sys-weight-medium",
            typefaceToken: "--sbt-sys-typeface-numeric",
            sample: "06/01",
            guidance: "Event calendar date labels.",
          },
          {
            label: "Event Detail MD",
            sizeToken: "--sbt-sys-typescale-event-detail-md-size",
            lineHeightToken: "--sbt-sys-typescale-event-detail-md-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "法說會 14:00",
            guidance: "Financial event table details.",
          },
          {
            label: "Control Symbol",
            sizeToken: "--sbt-sys-typescale-control-symbol-size",
            lineHeightToken: "--sbt-sys-typescale-control-symbol-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-plain",
            sample: "＋",
            guidance: "Compact control symbols and icon-adjacent glyphs.",
          },
          {
            label: "Status New",
            sizeToken: "--sbt-sys-typescale-status-new-size",
            lineHeightToken: "--sbt-sys-typescale-status-new-line-height",
            weightToken: "--sbt-sys-weight-bold",
            typefaceToken: "--sbt-sys-typeface-status-latin",
            sample: "NEW",
            guidance: "New badge text only.",
          },
          {
            label: "Stock Code SM",
            sizeToken: "--sbt-sys-typescale-stock-code-sm-size",
            lineHeightToken: "--sbt-sys-typescale-stock-code-sm-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-numeric",
            sample: "2330",
            guidance: "Default stock code display.",
          },
          {
            label: "Stock Code Compact",
            sizeToken: "--sbt-sys-typescale-stock-code-compact-size",
            lineHeightToken: "--sbt-sys-typescale-stock-code-compact-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-numeric",
            sample: "0050",
            guidance: "Stock code in compressed row contexts.",
          },
          {
            label: "Stock Code XS",
            sizeToken: "--sbt-sys-typescale-stock-code-xs-size",
            lineHeightToken: "--sbt-sys-typescale-stock-code-xs-line-height",
            weightToken: "--sbt-sys-weight-regular",
            typefaceToken: "--sbt-sys-typeface-numeric",
            sample: "2881",
            guidance: "Smallest stock-code context.",
          },
        ],
      },
    ],
  },
  spacingGuides: {
    eyebrow: "Foundations",
    title: "Spacing Guide",
    lead:
      "Spacing guidance for compact mobile-first trading surfaces. Use system spacing roles for shared layout rhythm and component tokens for component-specific slots.",
    rulesTitle: "Spacing operating rules",
    spacingTitle: "System spacing roles",
    groupTitle: "Spacing groups",
    tokenLabel: "Token",
    valueLabel: "Authored",
    resolvedLabel: "Resolved",
    usageLabel: "Use",
    unknownValue: "Unknown token",
    rules: [
      "Spacing roles are semantic aliases over the raw size scale. Prefer sys spacing in shared layouts and comp spacing in component slots.",
      "Small increments support dense financial rows. Avoid inflating gaps unless the component contract includes a larger spacing role.",
      "Hairline is a spacing token for 1px separators and borders; do not substitute it for a color or opacity token.",
      "Screen gutter, container, and section-gap roles are layout rhythm tokens. Keep them separate from internal row padding.",
    ],
    sections: [
      {
        title: "Core Increments",
        summary:
          "Small spacing roles cover dense rows, icon-label gaps, compact padding, and one-pixel separators.",
        roles: [
          {
            label: "None",
            token: "--sbt-sys-spacing-none",
            guidance: "Reset margin, padding, and list spacing.",
          },
          {
            label: "Hairline",
            token: "--sbt-sys-spacing-hairline",
            guidance: "One-pixel separators, borders, and divider thickness.",
          },
          {
            label: "XXS",
            token: "--sbt-sys-spacing-xxs",
            guidance: "Micro gaps inside compact controls.",
          },
          {
            label: "XXS Plus",
            token: "--sbt-sys-spacing-xxs-plus",
            guidance: "Three-pixel offset where the source uses a slightly larger micro gap.",
          },
          {
            label: "XXS Compact",
            token: "--sbt-sys-spacing-xxs-compact",
            guidance: "Compact three-pixel gaps with a distinct semantic slot.",
          },
          {
            label: "XS",
            token: "--sbt-sys-spacing-xs",
            guidance: "Default tiny gaps between icons, labels, and supporting metadata.",
          },
          {
            label: "S",
            token: "--sbt-sys-spacing-s",
            guidance: "Five-pixel dense row offsets.",
          },
          {
            label: "SM",
            token: "--sbt-sys-spacing-sm",
            guidance: "Small control padding and compact chip gaps.",
          },
          {
            label: "Icon Label LG",
            token: "--sbt-sys-spacing-icon-label-lg",
            guidance: "Icon-to-label spacing where the source needs a seven-pixel gap.",
          },
          {
            label: "MD",
            token: "--sbt-sys-spacing-md",
            guidance: "Default compact row and panel internal spacing.",
          },
          {
            label: "M",
            token: "--sbt-sys-spacing-m",
            guidance: "Medium internal spacing for denser composed rows.",
          },
          {
            label: "LG",
            token: "--sbt-sys-spacing-lg",
            guidance: "Eleven-pixel spacing role preserved from extracted evidence.",
          },
          {
            label: "L",
            token: "--sbt-sys-spacing-l",
            guidance: "Common list, card, and control horizontal padding.",
          },
          {
            label: "L Plus",
            token: "--sbt-sys-spacing-l-plus",
            guidance: "Thirteen-pixel inset where row evidence requires an asymmetric step.",
          },
        ],
      },
      {
        title: "Layout Rhythm",
        summary:
          "Layout spacing roles set shell gutters, section rhythm, and larger control spacing without inventing ad hoc values.",
        roles: [
          {
            label: "Screen Gutter",
            token: "--sbt-sys-spacing-screen-gutter",
            guidance: "Mobile screen side padding and Storybook panel rhythm.",
          },
          {
            label: "Segment Control X",
            token: "--sbt-sys-spacing-segment-control-x",
            guidance: "Horizontal inset for segmented-control style controls.",
          },
          {
            label: "XL",
            token: "--sbt-sys-spacing-xl",
            guidance: "Larger internal spacing and prominent control padding.",
          },
          {
            label: "Container XL",
            token: "--sbt-sys-spacing-container-xl",
            guidance: "Outer documentation shell and larger container padding.",
          },
          {
            label: "Control Content LG",
            token: "--sbt-sys-spacing-control-content-lg",
            guidance: "Large content gap inside control groups.",
          },
          {
            label: "Section Gap XL",
            token: "--sbt-sys-spacing-section-gap-xl",
            guidance: "Large vertical separation between major sections.",
          },
        ],
      },
    ],
  },
  shapeGuides: {
    eyebrow: "Foundations",
    title: "Shape Guide",
    lead:
      "Shape guidance for the current component evidence. Use system corner roles for shared geometry and component corner-radius tokens for component-specific slots.",
    rulesTitle: "Shape operating rules",
    cornerTitle: "System corner roles",
    groupTitle: "Shape groups",
    tokenLabel: "Token",
    valueLabel: "Authored",
    resolvedLabel: "Resolved",
    usageLabel: "Use",
    unknownValue: "Unknown token",
    rules: [
      "Corner roles encode product geometry, not decoration. Choose the semantic role that matches the component slot.",
      "Compact trading controls mostly use xxs, xs, and md corners. Avoid increasing radius without a component token.",
      "Label, pill, and full corners are distinct roles. Do not substitute a large radius when the component contract calls for a label radius.",
      "Top-only sheet corners use the top-xl role with only the leading top edges rounded.",
    ],
    sections: [
      {
        title: "Corner Semantics",
        summary:
          "System corner roles map raw radius values to reusable UI geometry for panels, controls, labels, sheets, and pill forms.",
        roles: [
          {
            label: "None",
            token: "--sbt-sys-shape-corner-none",
            guidance: "Square edges, resets, and cases where a component explicitly removes rounding.",
          },
          {
            label: "XXS",
            token: "--sbt-sys-shape-corner-xxs",
            guidance: "Small segmented controls, preview images, and tight badge details.",
          },
          {
            label: "XS",
            token: "--sbt-sys-shape-corner-xs",
            guidance: "Default compact controls, cells, dropdowns, buttons, and small cards.",
          },
          {
            label: "SM",
            token: "--sbt-sys-shape-corner-sm",
            guidance: "Dropdown controls and extracted component slots that need a five-pixel corner.",
          },
          {
            label: "MD",
            token: "--sbt-sys-shape-corner-md",
            guidance: "Panels, preview options, chart containers, and larger compact cards.",
          },
          {
            label: "LG",
            token: "--sbt-sys-shape-corner-lg",
            guidance: "Bottom-sheet headers, sheet tops, and larger container corners.",
          },
          {
            label: "Label",
            token: "--sbt-sys-shape-corner-label",
            guidance: "Attribute labels, valuation labels, and compact rounded label chips.",
          },
          {
            label: "Top XL",
            token: "--sbt-sys-shape-corner-top-xl",
            guidance: "Top-only rounding for sheet surfaces and stock detail panels.",
            topOnly: true,
          },
          {
            label: "Pill",
            token: "--sbt-sys-shape-corner-pill",
            guidance: "Pill-like action affordances and rounded guide swatches.",
          },
          {
            label: "Full",
            token: "--sbt-sys-shape-corner-full",
            guidance: "Fully rounded handles, badges, and controls that must resolve to capsules.",
          },
        ],
      },
    ],
  },
  shadowGuides: {
    eyebrow: "Foundations",
    title: "Shadow Guide",
    lead:
      "Shadow guidance for sticky edges and raised trading surfaces. Use system shadow roles for shared depth and component shadow slots for specific component behavior.",
    rulesTitle: "Shadow operating rules",
    shadowTitle: "Shadow roles",
    groupTitle: "Shadow groups",
    tokenLabel: "Token",
    valueLabel: "Authored",
    resolvedLabel: "Resolved",
    usageLabel: "Use",
    unknownValue: "Unknown token",
    rules: [
      "Shadows are functional depth cues for sticky columns and raised surfaces, not decorative card elevation.",
      "Sticky-edge shadows are directional and should be used only when content scrolls behind a fixed edge.",
      "Raised-surface shadow is reserved for evidenced floating or lifted surfaces. Do not add it to every panel.",
      "Component shadow tokens bind specific slots to system roles. Product code should consume those component tokens when available.",
    ],
    sections: [
      {
        title: "System Shadow Roles",
        summary:
          "System shadow roles map raw shadow values to shared depth behavior for sticky edges and raised surfaces.",
        roles: [
          {
            label: "Sticky edge",
            token: "--sbt-sys-shadow-sticky-edge",
            guidance: "Subtle directional shadow for sticky headers or columns.",
          },
          {
            label: "Sticky edge strong",
            token: "--sbt-sys-shadow-sticky-edge-strong",
            guidance: "Stronger directional shadow where sticky content needs more separation.",
          },
          {
            label: "Raised surface",
            token: "--sbt-sys-shadow-raised-surface",
            guidance: "Floating or lifted surfaces that sit above dense financial content.",
          },
        ],
      },
      {
        title: "Component Shadow Slots",
        summary:
          "Component shadow slots preserve the component contract while inheriting from system shadow roles.",
        roles: [
          {
            label: "Manual import header",
            token: "--sbt-comp-portfolio-manual-import-cell-header-shadow",
            guidance: "Sticky header edge inside the manual import cell.",
          },
          {
            label: "Manual import stock",
            token: "--sbt-comp-portfolio-manual-import-cell-stock-shadow",
            guidance: "Stronger sticky stock column edge inside manual import rows.",
          },
          {
            label: "Health check stock",
            token: "--sbt-comp-portfolio-health-check-cell-stock-shadow",
            guidance: "Sticky stock column depth inside portfolio health-check cells.",
          },
          {
            label: "Profit summary surface",
            token: "--sbt-comp-portfolio-profit-summary-surface-shadow",
            guidance: "Raised portfolio profit summary surface.",
          },
        ],
      },
    ],
  },
  sizeGuides: {
    eyebrow: "Foundations",
    title: "Size Guide",
    lead:
      "Size guidance for viewport, icon, region, control, and component layout dimensions. Use system size roles for shared sizing and component size slots for component-specific contracts.",
    rulesTitle: "Size operating rules",
    sizeTitle: "System size roles",
    groupTitle: "Size groups",
    tokenLabel: "Token",
    valueLabel: "Authored",
    resolvedLabel: "Resolved",
    usageLabel: "Use",
    unknownValue: "Unknown token",
    rules: [
      "Size roles represent fixed evidence-backed dimensions. Do not substitute spacing tokens for width, height, or icon size slots.",
      "Viewport and region sizes describe the mobile-first shell; they are not responsive breakpoint tokens.",
      "Icon sizes and control sizes are distinct roles. Keep icon glyph sizing separate from control hit-area sizing.",
      "Component layout sizes should stay in component slots when they describe a specific product component structure.",
    ],
    sections: [
      {
        title: "Viewport And Regions",
        summary:
          "Mobile viewport and persistent region dimensions define the compact trading shell and safe-area rhythm.",
        roles: [
          {
            label: "Compact viewport width",
            token: "--sbt-sys-size-viewport-compact-width",
            guidance: "Reference width for extracted mobile-first screens.",
            preview: "width",
          },
          {
            label: "Compact viewport height",
            token: "--sbt-sys-size-viewport-compact-height",
            guidance: "Reference height for compact mobile screen evidence.",
            preview: "height",
          },
          {
            label: "Status region height",
            token: "--sbt-sys-size-region-status-height",
            guidance: "Top status region height in mobile shell compositions.",
            preview: "height",
          },
          {
            label: "Header region height",
            token: "--sbt-sys-size-region-header-height",
            guidance: "Persistent app header region height.",
            preview: "height",
          },
          {
            label: "Footer region height",
            token: "--sbt-sys-size-region-footer-height",
            guidance: "Persistent footer or bottom navigation region height.",
            preview: "height",
          },
          {
            label: "Safe-area bottom height",
            token: "--sbt-sys-size-region-safe-area-bottom-height",
            guidance: "Bottom safe-area reservation for compact mobile layouts.",
            preview: "height",
          },
        ],
      },
      {
        title: "Icon Sizes",
        summary:
          "Icon sizes preserve dense control rhythm without inflating touch or control dimensions.",
        roles: [
          {
            label: "Icon micro",
            token: "--sbt-sys-size-icon-micro",
            guidance: "Tiny utility glyphs and compact affordances.",
            preview: "square",
          },
          {
            label: "Icon XXS",
            token: "--sbt-sys-size-icon-xxs",
            guidance: "Extra-small glyphs in dense rows.",
            preview: "square",
          },
          {
            label: "Icon XS",
            token: "--sbt-sys-size-icon-xs",
            guidance: "Small utility icons and sheet controls.",
            preview: "square",
          },
          {
            label: "Icon SM",
            token: "--sbt-sys-size-icon-sm",
            guidance: "Default small action and selection icons.",
            preview: "square",
          },
          {
            label: "Icon standard",
            token: "--sbt-sys-size-icon-standard",
            guidance: "Standard action icon size.",
            preview: "square",
          },
          {
            label: "Icon MD",
            token: "--sbt-sys-size-icon-md",
            guidance: "Medium icon size for larger controls.",
            preview: "square",
          },
          {
            label: "Icon compact LG",
            token: "--sbt-sys-size-icon-compact-lg",
            guidance: "Large compact icon slot where the evidence uses a 28px glyph.",
            preview: "square",
          },
          {
            label: "Icon LG",
            token: "--sbt-sys-size-icon-lg",
            guidance: "Large product icon size.",
            preview: "square",
          },
          {
            label: "Icon XL",
            token: "--sbt-sys-size-icon-xl",
            guidance: "Largest shared icon role in the current system.",
            preview: "square",
          },
        ],
      },
      {
        title: "Controls",
        summary:
          "Control size roles define compact action heights, widths, toggles, and border thickness.",
        roles: [
          {
            label: "Control compact height",
            token: "--sbt-sys-size-control-height-compact",
            guidance: "Compact chip and low-height control role.",
            preview: "height",
          },
          {
            label: "Control slim height",
            token: "--sbt-sys-size-control-height-slim",
            guidance: "Slim controls that sit inside dense rows.",
            preview: "height",
          },
          {
            label: "Control XS height",
            token: "--sbt-sys-size-control-height-xs",
            guidance: "Extra-small control height.",
            preview: "height",
          },
          {
            label: "Control SM height",
            token: "--sbt-sys-size-control-height-sm",
            guidance: "Small control height for dropdowns and filters.",
            preview: "height",
          },
          {
            label: "Control MD height",
            token: "--sbt-sys-size-control-height-md",
            guidance: "Medium form and action control height.",
            preview: "height",
          },
          {
            label: "Control SM width",
            token: "--sbt-sys-size-control-width-sm",
            guidance: "Small fixed-width control slot.",
            preview: "width",
          },
          {
            label: "Control MD width",
            token: "--sbt-sys-size-control-width-md",
            guidance: "Medium fixed-width control slot.",
            preview: "width",
          },
          {
            label: "Toggle width",
            token: "--sbt-sys-size-toggle-control-width",
            guidance: "Switch/toggle control width.",
            preview: "width",
          },
          {
            label: "Toggle height",
            token: "--sbt-sys-size-toggle-control-height",
            guidance: "Switch/toggle control height.",
            preview: "height",
          },
        ],
      },
      {
        title: "Component Layout",
        summary:
          "Component layout sizes are evidence-backed dimensions for high-structure product surfaces.",
        roles: [
          {
            label: "Bottom sheet width",
            token: "--sbt-sys-size-bottom-sheet-width",
            guidance: "Shared bottom-sheet surface width.",
            preview: "width",
          },
          {
            label: "Bottom sheet header height",
            token: "--sbt-sys-size-bottom-sheet-header-height",
            guidance: "Header region height inside bottom sheets.",
            preview: "height",
          },
          {
            label: "Bottom sheet drag handle width",
            token: "--sbt-sys-size-bottom-sheet-drag-handle-width",
            guidance: "Drag-handle width for bottom-sheet affordances.",
            preview: "width",
          },
          {
            label: "Market filter width",
            token: "--sbt-sys-size-market-filter-width",
            guidance: "Market filter strip width.",
            preview: "width",
          },
          {
            label: "Market filter height",
            token: "--sbt-sys-size-market-filter-height",
            guidance: "Market filter row height.",
            preview: "height",
          },
          {
            label: "Portfolio profit width",
            token: "--sbt-sys-size-portfolio-profit-width",
            guidance: "Portfolio profit summary composition width.",
            preview: "width",
          },
          {
            label: "Portfolio profit summary height",
            token: "--sbt-sys-size-portfolio-profit-summary-height",
            guidance: "Collapsed portfolio profit summary height.",
            preview: "height",
          },
          {
            label: "Portfolio profit ring LG",
            token: "--sbt-sys-size-portfolio-profit-ring-lg",
            guidance: "Large allocation ring size.",
            preview: "square",
          },
        ],
      },
    ],
  },
  opacityGuides: {
    eyebrow: "Foundations",
    title: "Opacity Guide",
    lead:
      "Opacity guidance for state overlays, alpha colors, and annotation-only transparent paints. Use state opacity roles for behavioral layering and color roles for authored alpha paints.",
    rulesTitle: "Opacity operating rules",
    opacityTitle: "Opacity and alpha roles",
    groupTitle: "Opacity groups",
    tokenLabel: "Token",
    valueLabel: "Authored",
    resolvedLabel: "Resolved",
    usageLabel: "Use",
    unknownValue: "Unknown token",
    rules: [
      "State opacity tokens describe layering strength; do not use them as color roles.",
      "Alpha color roles already include color and transparency. Use the named color role instead of combining color and opacity ad hoc.",
      "Annotation opacity roles are QA/spec-only. Do not ship annotation transparency as product UI chrome.",
      "Transparent roles are intentional paint values and should not be replaced with display none or removed fills.",
    ],
    sections: [
      {
        title: "State Opacity",
        summary:
          "State opacity roles provide reusable opacity strengths for overlays and annotation states.",
        roles: [
          {
            label: "None",
            token: "--sbt-sys-state-opacity-none",
            guidance: "Fully transparent state layer.",
            kind: "opacity",
          },
          {
            label: "Subtle",
            token: "--sbt-sys-state-opacity-subtle",
            guidance: "Subtle overlay strength.",
            kind: "opacity",
          },
          {
            label: "Medium",
            token: "--sbt-sys-state-opacity-medium",
            guidance: "Medium overlay strength for visible state layers.",
            kind: "opacity",
          },
          {
            label: "Annotation medium",
            token: "--sbt-sys-state-opacity-annotation-medium",
            guidance: "Medium annotation overlay strength for specs and QA.",
            kind: "opacity",
          },
          {
            label: "Annotation strong",
            token: "--sbt-sys-state-opacity-annotation-strong",
            guidance: "Strong annotation overlay strength for specs and QA.",
            kind: "opacity",
          },
        ],
      },
      {
        title: "Alpha Color Roles",
        summary:
          "Alpha color roles preserve authored transparency in outlines, transparent fills, and annotation paints.",
        roles: [
          {
            label: "Transparent",
            token: "--sbt-sys-color-transparent",
            guidance: "Explicit transparent paint role.",
            kind: "color",
          },
          {
            label: "Inverse outline subtle",
            token: "--sbt-sys-color-outline-inverse-subtle",
            guidance: "Subtle alpha separator on dark or inverse surfaces.",
            kind: "color",
          },
          {
            label: "Inverse outline",
            token: "--sbt-sys-color-outline-inverse",
            guidance: "Stronger alpha separator on dark or inverse surfaces.",
            kind: "color",
          },
          {
            label: "Primary outline subtle",
            token: "--sbt-sys-color-primary-outline-subtle",
            guidance: "Subtle alpha primary outline for warm action borders.",
            kind: "color",
          },
          {
            label: "Annotation fixed",
            token: "--sbt-sys-color-annotation-fixed",
            guidance: "Spec-only fixed annotation overlay.",
            kind: "color",
          },
          {
            label: "Annotation ratio",
            token: "--sbt-sys-color-annotation-ratio",
            guidance: "Spec-only ratio annotation overlay.",
            kind: "color",
          },
        ],
      },
    ],
  },
  strokeGuides: {
    eyebrow: "Foundations",
    title: "Border Guide",
    lead:
      "Border guidance for separators, control borders, outline colors, and active outlines. Pair width tokens with outline color roles instead of hardcoding border values.",
    rulesTitle: "Border operating rules",
    strokeTitle: "Border roles",
    groupTitle: "Border groups",
    widthLabel: "Width",
    colorLabel: "Color",
    valueLabel: "Authored",
    resolvedLabel: "Resolved",
    usageLabel: "Use",
    unknownValue: "Unknown token",
    rules: [
      "Border width and border color are separate token decisions. Do not hide a missing outline role inside a one-off border shorthand.",
      "Use hairline or control-border width for compact separators; use strong width only where the component contract calls for emphasis.",
      "Outline color roles describe contrast level. Do not use outline colors as filled surfaces.",
      "Primary outline roles are action/brand outlines, not generic warning or market-state borders.",
    ],
    sections: [
      {
        title: "Neutral Strokes",
        summary:
          "Neutral stroke roles cover separators, panel borders, controls, and stronger outlines on compact surfaces.",
        roles: [
          {
            label: "Hairline subtle",
            widthToken: "--sbt-sys-spacing-hairline",
            colorToken: "--sbt-sys-color-outline-subtle",
            guidance: "Lowest-emphasis divider or surface boundary.",
          },
          {
            label: "Hairline low",
            widthToken: "--sbt-sys-spacing-hairline",
            colorToken: "--sbt-sys-color-outline-low",
            guidance: "Default low-contrast panel and card border.",
          },
          {
            label: "Hairline middle",
            widthToken: "--sbt-sys-spacing-hairline",
            colorToken: "--sbt-sys-color-outline-middle",
            guidance: "Middle contrast separator in dense rows.",
          },
          {
            label: "Control outline",
            widthToken: "--sbt-sys-size-control-border-width",
            colorToken: "--sbt-sys-color-control-outline",
            guidance: "Default compact control border.",
          },
          {
            label: "Strong outline",
            widthToken: "--sbt-sys-size-control-border-width-strong",
            colorToken: "--sbt-sys-color-outline-strong",
            guidance: "Stronger control or selected boundary where evidenced.",
          },
          {
            label: "Contrast outline",
            widthToken: "--sbt-sys-size-control-border-width-strong",
            colorToken: "--sbt-sys-color-outline-contrast",
            guidance: "Highest neutral outline contrast in the current system.",
          },
        ],
      },
      {
        title: "Action And Inverse Strokes",
        summary:
          "Action and inverse strokes preserve brand or dark-surface outline behavior without inventing new border colors.",
        roles: [
          {
            label: "Primary subtle outline",
            widthToken: "--sbt-sys-size-control-border-width",
            colorToken: "--sbt-sys-color-primary-outline-subtle",
            guidance: "Subtle warm outline for primary action affordances.",
          },
          {
            label: "Primary pressed outline",
            widthToken: "--sbt-sys-size-control-border-width-strong",
            colorToken: "--sbt-sys-color-primary-outline-pressed",
            guidance: "Pressed primary outline state.",
          },
          {
            label: "Inverse subtle outline",
            widthToken: "--sbt-sys-spacing-hairline",
            colorToken: "--sbt-sys-color-outline-inverse-subtle",
            guidance: "Subtle alpha divider on dark or inverse surfaces.",
          },
          {
            label: "Inverse outline",
            widthToken: "--sbt-sys-spacing-hairline",
            colorToken: "--sbt-sys-color-outline-inverse",
            guidance: "Stronger alpha divider on dark or inverse surfaces.",
          },
        ],
      },
    ],
  },
  governance: {
    eyebrow: "Governance",
    title: "Storybook Architecture",
    lead:
      "This workspace is the design-system verification surface. Product source remains in tokens and design-system specs; Storybook proves the contract through browsable stories.",
    findingsTitle: "Discovered project conventions",
    workflowTitle: "Future development workflow",
    architectureTitle: "Folder contract",
    findings: [
      "Token prefix comes from .storybook/project.config.ts and uses three layers: ref, sys, and comp.",
      "Token inheritance is ref to sys to comp. Component tokens must never reference ref tokens directly.",
      "Starter evidence is intentionally small. Project-specific evidence should be added before broadening component coverage.",
      "Motion tokens and a named app grid class are not established yet, so Storybook does not introduce them.",
      "Component source and component stories are colocated under src/components/<component>/; page source and page stories are colocated under src/pages/<page>/.",
    ],
    workflow: [
      "Before creating a component story, check design-system/COMPONENT_INVENTORY.md and reuse an extracted component contract when available.",
      "If a state needs new visual semantics, add or approve sys and comp tokens first.",
      "Implement product components only after token mapping is confirmed.",
      "Every interactive component story should cover Default, Hover, FocusVisible, and Disabled when those states are evidenced.",
      "If evidence is missing, mark the state as missing instead of inventing the visual treatment.",
    ],
    folders: [
      "tokens/: CSS custom properties and the design-token source of truth.",
      "design-system/: evidence, architecture, inventory, and component specs.",
      "src/components/: component source, CSS, exports, and colocated component stories.",
      "src/pages/: page source, page CSS, and colocated page stories.",
      "src/stories/: foundations, governance, and shared Storybook guide content.",
      "src/stories/foundations/: token and foundation stories.",
      "src/stories/governance/: governance and workflow stories.",
      "src/storybook/: Storybook tooling only.",
    ],
  },
  componentCatalog: {
    eyebrow: "Governance",
    title: "Component Catalog",
    lead:
      "A browsable index of Storybook component categories, semantic roles, assembly hints, and AI-readable metadata used by every component story.",
    statsTitle: "Catalog coverage",
    categoriesLabel: "Categories",
    componentsLabel: "Components",
    metadataLabel: "AI metadata",
    metadataValue: "title, purpose, useWhen, dependencies, keywords",
    tableHeaders: {
      component: "Component",
      role: "Role",
      useWhen: "Use when",
      dependencies: "Dependencies",
      keywords: "Keywords",
    },
    emptyDependencies: "None",
  },
};
