import fs from "node:fs";
import path from "node:path";

const ADDON_NAME = "@harrychuang/storybook-addon-figma-export";
const GENERATED_MARKER = "Generated by design-system-to-storybook Figma export installer.";
const configExtensions = ["ts", "tsx", "js", "jsx", "mjs", "cjs"];

export function planFigmaExportWiring({ productRoot, fullReview }) {
  const storybookDir = path.join(productRoot, ".storybook");
  const mainPath = findConfigFile(storybookDir, "main");
  if (!mainPath) {
    throw new Error(
      `Cannot configure Figma export: no .storybook/main.{${configExtensions.join(",")}} file was found.`,
    );
  }
  const previewPath =
    findConfigFile(storybookDir, "preview") ?? path.join(storybookDir, "preview.ts");
  const mainWiringPath = path.join(storybookDir, "figma-export.main.mjs");
  const previewWiringPath = path.join(storybookDir, "figma-export.preview.mjs");
  const mainSource = fs.readFileSync(mainPath, "utf8");
  const previewSource = fs.existsSync(previewPath)
    ? fs.readFileSync(previewPath, "utf8")
    : "const preview = {};\n\nexport default preview;\n";

  return {
    files: [
      ownedGeneratedFile(mainWiringPath, renderMainWiring(fullReview)),
      ownedGeneratedFile(previewWiringPath, renderPreviewWiring(fullReview)),
      {
        filePath: mainPath,
        source: wrapDefaultExport(
          mainSource,
          "withFigmaExportMain",
          './figma-export.main.mjs',
        ),
      },
      {
        filePath: previewPath,
        source: wrapDefaultExport(
          previewSource,
          "withFigmaExportPreview",
          './figma-export.preview.mjs',
        ),
      },
    ],
    mainPath,
    previewPath,
    rendererNeutral: true,
    fullReview,
  };
}

export function applyFigmaExportWiring(plan) {
  for (const file of plan.files) {
    fs.mkdirSync(path.dirname(file.filePath), { recursive: true });
    fs.writeFileSync(file.filePath, file.source);
  }
  return {
    files: plan.files.map((file) => file.filePath),
    mainPath: plan.mainPath,
    previewPath: plan.previewPath,
    rendererNeutral: plan.rendererNeutral,
    fullReview: plan.fullReview,
  };
}

function findConfigFile(storybookDir, basename) {
  for (const extension of configExtensions) {
    const candidate = path.join(storybookDir, `${basename}.${extension}`);
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

function ownedGeneratedFile(filePath, source) {
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, "utf8");
    if (!existing.includes(GENERATED_MARKER)) {
      throw new Error(
        `Refusing to overwrite project-owned file ${filePath}. Move it or add the addon wiring manually.`,
      );
    }
  }
  return { filePath, source };
}

function wrapDefaultExport(source, helperName, helperModule) {
  const importLine = `import { ${helperName} } from "${helperModule}";`;
  if (
    source.includes(importLine) &&
    new RegExp(`export\\s+default\\s+${helperName}\\s*\\(`).test(source)
  ) {
    return source;
  }
  if (source.includes(helperName) || source.includes(helperModule)) {
    throw new Error(
      `Cannot safely update Storybook config because it contains partial ${helperName} wiring.`,
    );
  }

  let next = `${importLine}\n${source}`;
  const identifierExport = /export\s+default\s+([A-Za-z_$][\w$]*)\s*;?/;
  const identifierMatch = next.match(identifierExport);
  if (identifierMatch) {
    return ensureTrailingNewline(
      next.replace(
        identifierExport,
        `export default ${helperName}(${identifierMatch[1]});`,
      ),
    );
  }

  if (/export\s+default\s+(?:function|class)\b/.test(next)) {
    throw new Error(
      "Cannot safely wrap a default function/class Storybook config. Export a config object identifier and retry.",
    );
  }
  if (!/export\s+default\s+/.test(next)) {
    throw new Error(
      "Cannot safely configure Storybook because its config has no ESM default export.",
    );
  }

  const localName = helperName === "withFigmaExportMain"
    ? "__sbfxStorybookMain"
    : "__sbfxStorybookPreview";
  next = next.replace(
    /export\s+default\s+/,
    `const ${localName} = `,
  );
  return ensureTrailingNewline(
    `${next.trimEnd()}\n\nexport default ${helperName}(${localName});`,
  );
}

function renderMainWiring(fullReview) {
  if (!fullReview) {
    return `// ${GENERATED_MARKER}
const addonName = "${ADDON_NAME}";

export function withFigmaExportMain(config) {
  return {
    ...config,
    addons: [...new Set([...(config.addons ?? []), addonName])],
  };
}
`;
  }
  return `// ${GENERATED_MARKER}
import { createFigmaReviewStatusPlugin } from "${ADDON_NAME}/review-server";

const addonName = "${ADDON_NAME}";
const defaultReview = {
  apiPath: "/__figma_export_review_status",
  commentsApiPath: "/__figma_export_review_comments",
  commentsDir: "design-system/figma-export-review",
  commentsEnabled: true,
  filePath: "design-system/figma-export-review-status.json",
  name: "figma-export-review-status-api",
};

export function withFigmaExportMain(config, options = {}) {
  const projectReview = options.review ?? {};
  const review = {
    ...defaultReview,
    ...projectReview,
    filePath: projectReview.filePath ?? projectReview.statusFilePath ?? defaultReview.filePath,
  };
  const existingViteFinal = config.viteFinal;
  return {
    ...config,
    addons: [...new Set([...(config.addons ?? []), addonName])],
    async viteFinal(viteConfig, context) {
      const resolved = existingViteFinal
        ? await existingViteFinal.call(config, viteConfig, context)
        : viteConfig;
      return {
        ...resolved,
        plugins: [
          ...(resolved.plugins ?? []),
          createFigmaReviewStatusPlugin({
            apiPath: review.apiPath,
            filePath: review.filePath,
            name: review.name,
            commentsEnabled: review.commentsEnabled,
            commentsApiPath: review.commentsApiPath,
            commentsDir: review.commentsDir,
          }),
        ],
      };
    },
  };
}
`;
}

function renderPreviewWiring(fullReview) {
  if (!fullReview) {
    return `// ${GENERATED_MARKER}
import {
  createFigmaExportDecorator,
  createFigmaExportGlobalTypes,
  createFigmaExportInitialGlobals,
} from "${ADDON_NAME}";
import "${ADDON_NAME}/styles.css";

const defaultAddon = {
  storyTitlePrefix: false,
};

export function withFigmaExportPreview(preview, options = {}) {
  const addon = { ...defaultAddon, ...(options.addon ?? {}) };
  return {
    ...preview,
    decorators: [
      ...(preview.decorators ?? []),
      createFigmaExportDecorator(addon),
    ],
    globalTypes: {
      ...(preview.globalTypes ?? {}),
      ...createFigmaExportGlobalTypes(addon),
    },
    initialGlobals: {
      ...(preview.initialGlobals ?? {}),
      ...createFigmaExportInitialGlobals(addon),
    },
  };
}
`;
  }
  return `// ${GENERATED_MARKER}
import {
  createFigmaExportGlobalTypes,
  createFigmaExportInitialGlobals,
} from "${ADDON_NAME}";
import { createFigmaExportReviewDecorator } from "${ADDON_NAME}/review";
import "${ADDON_NAME}/styles.css";

const defaultAddon = {
  storyTitlePrefix: false,
  visualComments: {
    enabled: true,
    apiPath: "/__figma_export_review_comments",
    captureSelector: "#storybook-root",
    authorStorageKey: "sbfx:review-author",
  },
};
const defaultReview = {
  enabled: true,
  apiPath: "/__figma_export_review_status",
};

export function withFigmaExportPreview(preview, options = {}) {
  const addon = {
    ...defaultAddon,
    ...(options.addon ?? {}),
    visualComments: {
      ...defaultAddon.visualComments,
      ...(options.review?.visualComments ?? {}),
      ...(options.addon?.visualComments ?? {}),
    },
  };
  const review = {
    ...defaultReview,
    ...(options.review ?? {}),
    visualComments: addon.visualComments,
  };
  return {
    ...preview,
    decorators: [
      ...(preview.decorators ?? []),
      createFigmaExportReviewDecorator(addon, review),
    ],
    globalTypes: {
      ...(preview.globalTypes ?? {}),
      ...createFigmaExportGlobalTypes(addon),
    },
    initialGlobals: {
      ...(preview.initialGlobals ?? {}),
      ...createFigmaExportInitialGlobals(addon),
    },
  };
}
`;
}

function ensureTrailingNewline(value) {
  return value.endsWith("\n") ? value : `${value}\n`;
}
