import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { parseEnvText, parseFigmaUrl } from './lib/workspace.js'

function readFlag(name) {
  const args = process.argv.slice(2)
  const idx = args.indexOf(name)
  return idx >= 0 ? args[idx + 1] : undefined
}

const url = readFlag('--url')
const pat = readFlag('--pat') ?? ''

if (!url) {
  console.error('Usage: npm run figma:configure -- --url "<figma-url>" [--pat "<figma-pat>"]')
  process.exit(1)
}

const parsed = parseFigmaUrl(url)
const rootDir = process.cwd()
const envPath = path.join(rootDir, '.env.local')

let existing = {}
try {
  existing = parseEnvText(await readFile(envPath, 'utf8'))
} catch {
  existing = {}
}

const merged = {
  ...existing,
  FIGMA_FILE_URL: url,
  FIGMA_NODE_ID: parsed.nodeId,
  FIGMA_PAT: pat || existing.FIGMA_PAT || ''
}

const lines = [
  '# Generated by scripts/configure-figma.mjs',
  `FIGMA_FILE_URL=${merged.FIGMA_FILE_URL}`,
  `FIGMA_NODE_ID=${merged.FIGMA_NODE_ID}`,
  `FIGMA_PAT=${merged.FIGMA_PAT}`
]

if (existing.OPENAI_API_KEY) lines.push(`OPENAI_API_KEY=${existing.OPENAI_API_KEY}`)
if (existing.ANTHROPIC_API_KEY) lines.push(`ANTHROPIC_API_KEY=${existing.ANTHROPIC_API_KEY}`)

await writeFile(envPath, lines.join('\n') + '\n', 'utf8')

console.log(`Configured Figma source for fileKey=${parsed.fileKey} nodeId=${parsed.nodeId}`)
