import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { getFigmaAuthMode, parseEnvText, parseFigmaUrl } from './lib/workspace.js'

function readFlag(name) {
  const args = process.argv.slice(2)
  const idx = args.indexOf(name)
  return idx >= 0 ? args[idx + 1] : undefined
}

const url = readFlag('--url')
const pat = readFlag('--pat') ?? ''
const authModeInput = readFlag('--auth-mode') ?? ''
const authMode = authModeInput.trim().toLowerCase()

if (!url) {
  console.error('Usage: npm run figma:configure -- --url "<figma-url>" [--pat "<figma-pat>"] [--auth-mode "connector"]')
  process.exit(1)
}

const parsed = parseFigmaUrl(url)
const rootDir = process.cwd()
const envPath = path.join(rootDir, '.env.local')

let existing = {}
try {
  existing = parseEnvText(await readFile(envPath, 'utf8'))
} catch {
  existing = {}
}

const merged = {
  ...existing,
  FIGMA_FILE_URL: url,
  FIGMA_NODE_ID: parsed.nodeId,
  FIGMA_PAT: pat || existing.FIGMA_PAT || '',
  FIGMA_AUTH_MODE: authMode || existing.FIGMA_AUTH_MODE || ''
}

const lines = [
  '# Generated by scripts/configure-figma.mjs',
  '# Use FIGMA_PAT, or set FIGMA_AUTH_MODE=connector when your tool already has authenticated Figma MCP/connector access.',
  `FIGMA_FILE_URL=${merged.FIGMA_FILE_URL}`,
  `FIGMA_NODE_ID=${merged.FIGMA_NODE_ID}`,
  `FIGMA_PAT=${merged.FIGMA_PAT}`,
  `FIGMA_AUTH_MODE=${getFigmaAuthMode(merged) || merged.FIGMA_AUTH_MODE}`
]

if (existing.OPENAI_API_KEY) lines.push(`OPENAI_API_KEY=${existing.OPENAI_API_KEY}`)
if (existing.ANTHROPIC_API_KEY) lines.push(`ANTHROPIC_API_KEY=${existing.ANTHROPIC_API_KEY}`)

await writeFile(envPath, lines.join('\n') + '\n', 'utf8')

console.log(`Configured Figma source for fileKey=${parsed.fileKey} nodeId=${parsed.nodeId}`)
if (!merged.FIGMA_PAT && getFigmaAuthMode(merged) !== 'connector') {
  console.log('Warning: FIGMA_PAT is empty and FIGMA_AUTH_MODE is not connector; add FIGMA_PAT or set FIGMA_AUTH_MODE=connector before Figma-first automation or Phase 0')
}
