// Generated by scripts/init-storybook-template.mjs. Safe to regenerate.
export type StorybookTemplateProjectConfig = {
  project: {
    projectName: string;
    packageName: string;
    tokenPrefix: string;
    componentClassPrefixes: string[];
  };
  storybook: {
    stories: string[];
    staticDirs: string[];
    themeDataAttribute: string;
    backgrounds: {
      dark: {
        name: string;
        value: string;
      };
      light: {
        name: string;
        value: string;
      };
    };
    storySortOrder: unknown[];
  };
  figmaExport: {
    addon: {
      absoluteFidelityComponents: string[];
      componentClassPrefixes: string[];
      embeddedSvgByDataGraphic: Record<string, string>;
      storyTitlePrefix: string[] | false;
    };
    review: {
      apiPath: string;
      commentsApiPath: string;
      commentsDir: string;
      commentsEnabled: boolean;
      visualComments: {
        enabled: boolean;
        apiPath: string;
        captureSelector: string;
        authorStorageKey: string;
      };
      enabled: boolean;
      pluginName: string;
      statusFilePath: string;
    };
    source: {
      designSystemFileUrlFallback: string;
      nodeOverrides: Record<string, string>;
    };
  };
  prototypeInspector: {
    addonName: string;
    flowLayoutSchemaName: string;
    previewHeightCssVariable: string;
    routePreviewSelector: string;
  };
  catalog: {
    componentStoriesRoot: string;
  };
};

export function defineStorybookTemplateProjectConfig(
  config: StorybookTemplateProjectConfig,
): StorybookTemplateProjectConfig {
  return config;
}

export const storybookTemplateProjectConfig =
  defineStorybookTemplateProjectConfig({
  "project": {
    "projectName": "Storybook Template",
    "packageName": "storybook-template",
    "tokenPrefix": "sbt",
    "componentClassPrefixes": [
      "sbt-"
    ]
  },
  "storybook": {
    "stories": [
      "../src/stories/governance/*.stories.@(js|jsx|mjs|ts|tsx)",
      "../src/stories/foundations/TemplateFoundation.stories.@(js|jsx|mjs|ts|tsx)",
      "../src/components/**/*.stories.@(js|jsx|mjs|ts|tsx)",
      "../src/pages/prototypes/example-prototype/*.stories.@(js|jsx|mjs|ts|tsx)"
    ],
    "staticDirs": [
      "../tokens",
      "../design-system"
    ],
    "themeDataAttribute": "storybookTemplateTheme",
    "backgrounds": {
      "dark": {
        "name": "Dark theme",
        "value": "var(--sbt-ref-color-neutral-12)"
      },
      "light": {
        "name": "Light theme",
        "value": "var(--sbt-ref-color-neutral-100)"
      }
    },
    "storySortOrder": [
      "Governance",
      [
        "Storybook Architecture",
        "Component Catalog"
      ],
      "Foundations",
      "Components",
      [
        "Examples"
      ],
      "Pages",
      [
        "Prototypes"
      ]
    ]
  },
  "figmaExport": {
    "addon": {
      "absoluteFidelityComponents": [],
      "componentClassPrefixes": [
        "sbt-"
      ],
      "embeddedSvgByDataGraphic": {},
      "storyTitlePrefix": [
        "Components/",
        "Pages/"
      ]
    },
    "review": {
      "apiPath": "/__sbt_figma_review_status",
      "commentsApiPath": "/__figma_export_review_comments",
      "commentsDir": "design-system/figma-export-review",
      "commentsEnabled": true,
      "visualComments": {
        "enabled": true,
        "apiPath": "/__figma_export_review_comments",
        "captureSelector": "#storybook-root",
        "authorStorageKey": "sbfx:review-author"
      },
      "enabled": true,
      "pluginName": "sbt-figma-review-status-api",
      "statusFilePath": "design-system/figma-export-review-status.json"
    },
    "source": {
      "designSystemFileUrlFallback": "",
      "nodeOverrides": {}
    }
  },
  "prototypeInspector": {
    "addonName": "storybook-template/prototype-inspector",
    "flowLayoutSchemaName": "storybook-template.prototype-flow-layout",
    "previewHeightCssVariable": "--prototype-inspector-viewport-compact-height",
    "routePreviewSelector": "[data-prototype-route-preview=\"true\"]"
  },
  "catalog": {
    "componentStoriesRoot": "src/components"
  }
});
